const UserActionTypes = {
  SET_CURRENT_USER: "SET_CURRENT_USER",
  SET_TOKEN: "SET_TOKEN",

  REGISTER_START: "REGISTER_START",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAILURE: "REGISTER_FAILURE",

  LOG_IN_START: "LOG_IN_START",
  LOG_IN_SUCCESS: "LOG_IN_SUCCESS",
  LOG_IN_FAILURE: "LOG_IN_FAILURE",

  LOG_OUT_START: "LOG_OUT_START",
  LOG_OUT_SUCCESS: "LOG_OUT_SUCCESS",
  LOG_OUT_FAILURE: "LOG_OUT_FAILURE",

  SET_IS_LOGGED_IN: "SET_IS_LOGGED_IN",
  SET_IS_LOADING: "SET_IS_LOADING"
};
export default UserActionTypes;
