const WorkoutActionTypes = {
    GET_JOURNAL_START: "GET_JOURNAL_START",
    GET_JOURNAL_SUCCESS: "GET_JOURNAL_SUCCESS",
    GET_JOURNAL_FAILURE: "GET_JOURNAL_FAILURE",

    SET_IS_LOADING: "SET_IS_LOADING",

    ADD_WORKOUT_START: "ADD_WORKOUT_START",
    ADD_WORKOUT_SUCCESS: "ADD_WORKOUT_SUCCESS",
    ADD_WORKOUT_FAILURE: "ADD_WORKOUT_FAILURE"  
}

export default WorkoutActionTypes